
export const products = [
  '',
  "Holba",
  "Zubr",
  "Litovel Premium",
  "Litovel Dark",
  "Litovel Citron",
  "Desperados",
  "West Cost IPA",
  "Sour Mango",
  "Double IPA",
  "Piwo bezglutenowe",
  "Litovel Pszeniczne",
  "Żywiec Biały",
  "Heineken 00",
  "Cieszyn Pszeniczne",
  "Holba Free",
  "Dzik",
  "Spirytus",
  "Wyborowa",
  "Soplica Śliwkowa",
  "Soplica Kawowa",
  "Soplica Pigwowa",
  "Soplica Malinowa",
  "Soplica wiśniowa",
  "Soplica orzech laskowy", 
  "Żubrówka Bison Grass",
  "Żołądkowa Gorzka",
  "Żołądkowa Miętowa",
  "Becherovka",
  "Jagermeister",
  "Seagrams",
  "Bombay",
  "Capitan Morgan Dark",
  "Capitan Morgan Spiced",
  "Havana Club",
  "Johnny Walker",
  "Jack Daniels",
  "Jim Beam",
  "Jameson",
  "Wild Turky",
  "Stock 84",
  "Pliska",
  "Proper Twelve",
  "Ballantines",
  "Baileys",
  "Khalua",
  "Malibu",
  "Sierra Silver",
  "Sierra Reposado",
  "Śliwowica Passover",
  "Cabernet Savinione",
  "Chardonnay",
  "Martini Bianco",
  "Martini Dry",
  "Coca cola",
  "Cola Zero",
  "Tonik",
  "Sprite",
  "Fanta",
  "Red bull",
  "Red bull light",
  "Sok pamarańczowy",
  "Sok grejfrutowy",
  "Sok jabłkowy",
  "Sok porzeczkowy",
  "Woda Kinga niegazowana",
  "Woda Kinga gazowana",
  "Kawa",
  "Paluszki",
  "Orzeszki ziemne",
];

export const productType = [
  "",
  "Wódka",
  "Gin",
  "Tequila",
  "Whisky",
  "Brandy",
  "Burbon",
  "Rum",
  "Likier",
  "Piwo",
  "Cydr",
  "Wino",
  "Napój bezalkoholowy",
  "Przekąska",
];

export const packages = [
  "",
  "butelka 0.5 L",
  "butelka 0.7 L",
  "butelka 0.75 L",
  "butelka 1 L",
  "butelka 0.4 L",
  "butelka 0.33 L",
  "butelka 0.3 L",
  "butelka 0.25 L",
  "puszka 0.5 L",
  "puszka 0.33 L",
  "puszka 0.25 L",
  "puszka 0.2 L",
  "kega 30 L",
  "sztuka",
  "opakowanie"
];