
export const products = [
  '',
  "Holba",
  "Zubr",
  "Litovel Premium",
  "Litovel Premium Dark",
  "Litovel Citron",
  "Desperados",
  "West Cost IPA",
  "Sour Mango",
  "Double IPA",
  "Piwo bezglutenowe",
  "Litovel Pszeniczne",
  "Żywiec Biały",
  "Cieszyn Pszeniczne",
  "Holba Free",
  "Spirytus",
  "Wyborowa",
  "Soplica Śliwkowa",
  "Soplica Kawowa",
  "Soplica Pigwowa",
  "Soplica Malinowa",
  "Żubrówka - Bison Grass",
  "Żołądkowa Gorzka",
  "Żołądkowa Miętowa",
  "Becherovka",
  "Jegermaister",
  "Gin Seagrams",
  "Gin Bombay",
  "Capitan Morgan Dark",
  "Capitan Morgan Spiced",
  "Havana Club",
  "Johnny Walker",
  "Jack Daniels",
  "Jim Beam",
  "Jameson",
  "Proper Twelve",
  "Ballantines",
  "Baileys",
  "Khalua",
  "Malibu",
  "Tequila Sierra Silver",
  "Tequila Sierra Reposado",
  "Śliwowica Passover",
  "Cabernet Savinione",
  "Chardonnay",
  "Martini Bianco",
  "Martini Dry",
  "Coca cola",
  "Cola Zero",
  "Tonik",
  "Sprite",
  "Fanta",
  "Red bull",
  "Red bull light",
  "Sok pamarańczowy",
  "Sok grejfrutowy",
  "Sok jabłkowy",
  "Sok porzeczkowy",
  "Woda Kinga niegazowana",
  "Woda Kinga gazowana",
  "Kawa",
  "Paluszki",
  "Orzeszki ziemne",
];

export const productType = [
  "",
  "Wódka",
  "Gin",
  "Tequila",
  "Whisky",
  "Likier",
  "Piwo",
  "Cydr",
  "Wino",
  "Napój bezalkoholowy",
  "Przekąska",
];

export const packages = [
  "",
  "butelka 1 L",
  "butelka 0.7 L",
  "butelka 0.5 L",
  "butelka 0.4 L",
  "butelka 0.33 L",
  "butelka 0.3 L",
  "butelka 0.25 L",
  "puszka 0.5 L",
  "puszka 0.33 L",
  "puszka 0.25 L",
  "puszka 0.2 L",
  "kega 30 L",
  "sztuka",
  "opakowanie"
];